language: python
python:
  - "2.7"
install: "pip install -r requirements.txt --use-mirrors"
script: python travis.py
before_script:
  - wget https://commondatastorage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.4.zip -nv
  - unzip -q google_appengine_1.9.4.zip